import { z } from 'zod';
export type Coordinate=[number,number,number?];
export type Waypoint={id:string;coordinate:Coordinate;name:string;mode:'routed'|'manual'};
export type Annotation={name:string;coordinate:Coordinate};
export type Segment={mode:'routed'|'manual'|'imported';coordinates:Coordinate[]};
export type Route={schemaVersion:1;id:string;name:string;description:string;tags:string[];favorite:boolean;createdAt:string;updatedAt:string;source:'planned'|'gpx';shape:'point'|'loop'|'return';points:Waypoint[];markers:Annotation[];segments:Segment[];pace:number;status:'empty'|'valid'|'stale';provider:string};
export const uid=()=>crypto.randomUUID();
export function emptyRoute():Route {const now=new Date().toISOString();return {schemaVersion:1,id:uid(),name:'',description:'',tags:[],favorite:false,createdAt:now,updatedAt:now,source:'planned',shape:'point',points:[],markers:[],segments:[],pace:360,status:'empty',provider:'openrouteservice · foot-walking'};}
export function haversine(a:Coordinate,b:Coordinate){const r=Math.PI/180;const dLat=(b[1]-a[1])*r,dLon=(b[0]-a[0])*r;const h=Math.sin(dLat/2)**2+Math.cos(a[1]*r)*Math.cos(b[1]*r)*Math.sin(dLon/2)**2;return 6371008.8*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
export const distance=(segments:Segment[])=>segments.reduce((sum,s)=>sum+s.coordinates.reduce((d,p,i)=>d+(i?haversine(s.coordinates[i-1],p):0),0),0);
export const km=(m:number)=>(m/1000).toLocaleString('nl-NL',{minimumFractionDigits:2,maximumFractionDigits:2});
export const duration=(meters:number,pace:number)=>Math.round(meters/1000*pace/60);
export const paceText=(pace:number)=>`${Math.floor(pace/60)}:${String(pace%60).padStart(2,'0')}`;
export function reverseRoute(route:Route):Route{return {...route,points:[...route.points].reverse().map((p,i,arr)=>({...p,mode:i?route.points[route.points.length-i].mode:arr[0].mode})),segments:[...route.segments].reverse().map(s=>({...s,coordinates:[...s.coordinates].reverse()}))};}
export function exportGPX(route:Route){if(route.status!=='valid'||!route.segments.length)throw Error('Bereken eerst een geldige, actuele route.');const esc=(s:string)=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));const pts=(c:Coordinate,tag:string)=>`<${tag} lat="${c[1]}" lon="${c[0]}">${c[2]!==undefined?`<ele>${c[2]}</ele>`:''}</${tag}>`;return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Looply" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>${esc(route.name||'Mijn route')}</name><desc>${esc(route.description)}</desc></metadata>${[...route.points,...(route.markers||[])].map(p=>`<wpt lat="${p.coordinate[1]}" lon="${p.coordinate[0]}">${p.coordinate[2]!==undefined?`<ele>${p.coordinate[2]}</ele>`:''}<name>${esc(p.name)}</name></wpt>`).join('')}<trk><name>${esc(route.name||'Mijn route')}</name><desc>${esc(route.description)}</desc>${route.segments.map(s=>`<trkseg>${s.coordinates.map(c=>pts(c,'trkpt')).join('')}</trkseg>`).join('')}</trk></gpx>`;}
const coordinateSchema=z.tuple([z.number().min(-180).max(180),z.number().min(-90).max(90),z.number().optional()]);
export const routeSchema=z.object({schemaVersion:z.literal(1),id:z.string(),name:z.string(),description:z.string(),tags:z.array(z.string()),favorite:z.boolean(),createdAt:z.string(),updatedAt:z.string(),source:z.enum(['planned','gpx']),shape:z.enum(['point','loop','return']),points:z.array(z.object({id:z.string(),coordinate:coordinateSchema,name:z.string(),mode:z.enum(['routed','manual'])})).max(50),markers:z.array(z.object({name:z.string(),coordinate:coordinateSchema})).default([]),segments:z.array(z.object({mode:z.enum(['routed','manual','imported']),coordinates:z.array(coordinateSchema).min(2).max(100000)})),pace:z.number().min(120).max(1800),status:z.enum(['empty','valid','stale']),provider:z.string()});
export function parseBackup(text:string):Route[]{if(new Blob([text]).size>30*1024*1024)throw Error('Backup is groter dan 30 MiB.');const result=z.object({version:z.literal(1),routes:z.array(routeSchema).max(1000)}).safeParse(JSON.parse(text));if(!result.success)throw Error('Ongeldige backup of onbekende schemaversie.');return result.data.routes;}
export async function download(text:string,name:string,type:string){const file=new File([text],name,{type});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file]});return;}catch(e){if((e as Error).name==='AbortError')return;}}const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
