import {useEffect,useRef,useState} from 'react';
import {Map, Marker, ScaleControl, NavigationControl, LngLatBounds, type GeoJSONSource, setWorkerUrl} from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
setWorkerUrl(workerUrl);
import type {Coordinate,Route} from './domain';
export type MapHandle={fly:(coordinate:Coordinate)=>void;fit:()=>void;zoom:(delta:number)=>void};
export default function MapCanvas({route,onPoint,onSelect,onMove,handle,adding,fitSignal,location,dark=false,onPan}:{route:Route;onPoint:(p:Coordinate)=>void;onSelect:(i:number)=>void;onMove:(i:number,c:Coordinate)=>void;handle:React.RefObject<MapHandle|null>;adding:boolean;fitSignal:number;location:{coordinate:Coordinate;accuracy:number}|null;dark?:boolean;onPan:()=>void}){
const container=useRef<HTMLDivElement>(null),map=useRef<Map|null>(null),current=useRef({route,onPoint,onSelect,onMove,adding,onPan});current.current={route,onPoint,onSelect,onMove,adding,onPan};const [ready,setReady]=useState(false),[error,setError]=useState('');const markers=useRef<Marker[]>([]);
useEffect(()=>{if(!container.current)return;let m:Map;try{let center:Coordinate=[4.887,52.363];let zoom=13.2;try{const camera=JSON.parse(localStorage.getItem('looply-camera')||'null');if(camera){center=camera.center;zoom=camera.zoom;}}catch{}m=new Map({container:container.current,style:'https://tiles.openfreemap.org/styles/positron',center:center as [number,number],zoom,minZoom:2,maxZoom:19,attributionControl:{compact:true}});map.current=m;m.addControl(new ScaleControl({maxWidth:100,unit:'metric'}),'bottom-left');m.addControl(new NavigationControl({showZoom:false,visualizePitch:false}),'bottom-right');m.on('load',()=>{for(const layer of m.getStyle().layers){if(layer.type==='fill'&&/water/.test(layer.id)&&!/bridge/.test(layer.id))m.setPaintProperty(layer.id,'fill-color','#cbdedb');if(layer.type==='fill'&&/park|landcover.*grass|landcover.*wood|landuse.*park/.test(layer.id))m.setPaintProperty(layer.id,'fill-color','#dce6c9');}setReady(true);setError('');});m.on('error',()=>{setError(navigator.onLine?'Een kaartonderdeel kon niet worden geladen. Je kunt de pagina opnieuw laden.':'Je bent offline. De achtergrondkaart kan ontbreken.');});m.on('click',e=>{if(current.current.adding)current.current.onPoint([e.lngLat.lng,e.lngLat.lat]);});m.on('dragstart',()=>current.current.onPan());m.on('moveend',()=>{try{localStorage.setItem('looply-camera',JSON.stringify({center:m.getCenter().toArray(),zoom:m.getZoom()}))}catch{}});handle.current={fly:c=>m.flyTo({center:c as [number,number],zoom:15}),fit:()=>{const coords=current.current.route.segments.flatMap(s=>s.coordinates).concat(current.current.route.points.map(p=>p.coordinate),(current.current.route.markers||[]).map(p=>p.coordinate));if(coords.length){const bounds=new LngLatBounds();coords.forEach(c=>bounds.extend(c as [number,number]));m.fitBounds(bounds,{padding:85,maxZoom:16,duration:700});}else m.flyTo({center:[4.887,52.363],zoom:13.2});},zoom:d=>m.zoomTo(m.getZoom()+d)};}catch{setError('De kaart vereist WebGL. Probeer een recente browser; je opgeslagen routes blijven beschikbaar.');}return()=>{m?.remove();handle.current=null;};},[]);
useEffect(()=>{const m=map.current;if(!m||!ready)return;const data:Parameters<GeoJSONSource['setData']>[0]={type:'FeatureCollection',features:route.segments.map(s=>({type:'Feature',properties:{manual:s.mode==='manual'},geometry:{type:'LineString',coordinates:s.coordinates.map(c=>[c[0],c[1]])}}))};if(m.getSource('route'))(m.getSource('route') as GeoJSONSource).setData(data);else{m.addSource('route',{type:'geojson',data});m.addLayer({id:'route-halo',type:'line',source:'route',paint:{'line-color':'#fff','line-width':9,'line-opacity':.9},layout:{'line-join':'round','line-cap':'round'}});m.addLayer({id:'route-line',type:'line',source:'route',filter:['!=','manual',true],paint:{'line-color':'#26815e','line-width':5},layout:{'line-join':'round','line-cap':'round'}});m.addLayer({id:'route-manual',type:'line',source:'route',filter:['==','manual',true],paint:{'line-color':'#be843a','line-width':4,'line-dasharray':[2,2]},layout:{'line-join':'round','line-cap':'round'}});}m.setPaintProperty('route-line','line-opacity',route.status==='stale'?.45:1);m.setPaintProperty('route-manual','line-opacity',route.status==='stale'?.45:1);markers.current.forEach(marker=>marker.remove());markers.current=[];route.points.forEach((p,i)=>{const el=document.createElement('button');el.className=`waypoint-marker ${i===0?'start':i===route.points.length-1?'finish':''}`;el.textContent=i===0?'A':i===route.points.length-1?'B':String(i);el.title=p.name;el.setAttribute('aria-label',`Selecteer ${p.name}`);el.onclick=e=>{e.stopPropagation();current.current.onSelect(i);};const marker=new Marker({element:el,draggable:true}).setLngLat(p.coordinate as [number,number]).addTo(m);marker.on('dragend',()=>{const c=marker.getLngLat();current.current.onMove(i,[c.lng,c.lat]);});markers.current.push(marker);});(route.markers||[]).forEach(p=>{const el=document.createElement('div');el.className='annotation-marker';el.title=p.name;el.textContent='◆';markers.current.push(new Marker({element:el}).setLngLat(p.coordinate as [number,number]).addTo(m));});},[route,ready]);
useEffect(()=>{map.current?.getCanvas().style.setProperty('cursor',adding?'crosshair':'grab');},[adding,ready]);
useEffect(()=>{if(fitSignal&&ready)handle.current?.fit();},[fitSignal,ready]);
useEffect(()=>{if(!map.current||!location)return;const el=document.createElement('div');el.className='location-dot';const marker=new Marker({element:el}).setLngLat(location.coordinate as [number,number]).addTo(map.current);const m=map.current;const ring=Array.from({length:65},(_,i)=>{const angle=i/64*Math.PI*2;return [location.coordinate[0]+Math.cos(angle)*location.accuracy/(111320*Math.cos(location.coordinate[1]*Math.PI/180)),location.coordinate[1]+Math.sin(angle)*location.accuracy/111320]});const data={type:'Feature' as const,properties:{},geometry:{type:'Polygon' as const,coordinates:[ring]}};if(ready){if(m.getSource('accuracy'))(m.getSource('accuracy') as GeoJSONSource).setData(data);else{m.addSource('accuracy',{type:'geojson',data});m.addLayer({id:'accuracy-fill',source:'accuracy',type:'fill',paint:{'fill-color':'#4185cb','fill-opacity':.12}});}}return()=>{marker.remove()};},[location,ready]);
useEffect(()=>{container.current?.classList.toggle('map-muted',dark)},[dark]);
return <><div className="map-canvas" ref={container}/>{error&&<div className="map-error" role="alert">{error}</div>}</>;
}
