import {ArrowRight,ArrowUpRight,ArrowLeftRight,Download,Info,MoveUpRight,Repeat2,Route,Settings} from 'lucide-react';
export default function RouteGuide({onSettings,onClose}:{onSettings:()=>void;onClose:()=>void}){
return <><div className="eyebrow">VAN IDEE NAAR EERSTE STAP</div><h2 id="modal-title">Kies jouw soort rondje<span>.</span></h2><p>Je kiest eerst de routevorm. Daarna bepaal je per nieuw segment of Looply de paden volgt of een handmatige rechte lijn maakt.</p>
<div className="guide-start"><strong>Zo begin je</strong><ol><li>Zoek een adres of tik op de kaart in de modus <strong>Route tekenen</strong>. Een zoekresultaat centreert alleen de kaart; kies daarna <strong>Punt toevoegen</strong>.</li><li>Voeg je start en de plaatsen waar je langs wilt toe. Via <strong>Kies je startpunt</strong> of <strong>Routepunt toevoegen</strong> kun je ook coördinaten invoeren.</li><li>Kies hieronder de routevorm die bij je plan past.</li></ol></div>
<div className="guide-route"><div className="guide-title"><MoveUpRight size={20}/><h3>A naar B</h3><span>Enkele reis</span></div><div className="guide-diagram" aria-label="Van start A via tussenpunt naar eind B"><b>A</b><i/><span>1</span><i/><b>B</b></div><p>Begin en eindig op verschillende plekken. Looply verbindt je punten in de gekozen volgorde.</p><p><strong>Voorbeeld:</strong> van huis via het park naar het station. Kies <strong>A naar B</strong>, voeg je start, eventuele tussenpunten en je eindpunt toe.</p></div>
<div className="guide-route"><div className="guide-title"><Repeat2 size={20}/><h3>Rondje</h3><span>Terug naar je start</span></div><div className="guide-diagram" aria-label="Van A via punt 1 en punt 2 terug naar A"><b>A</b><i/><span>1</span><i/><span>2</span><i/><b>A</b></div><p>Looply verbindt het laatste punt weer met je start. Met <strong>Volg de paden</strong> wordt ook die terugverbinding berekend; een handmatig laatste segment maakt ook de sluiting handmatig.</p><p><strong>Voorbeeld:</strong> een lus langs de noord- en zuidkant van een park. Kies <strong>Rondje</strong> en plaats tussenpunten aan beide kanten. Een rondje met alleen twee punten kan dezelfde weg heen en terug gebruiken.</p><p className="guide-note">Je bepaalt zelf waar je langs loopt. Looply genereert geen automatisch rondje van bijvoorbeeld 5 km.</p></div>
<div className="guide-route"><div className="guide-title"><ArrowLeftRight size={20}/><h3>Heen & terug</h3><span>Dezelfde weg terug</span></div><div className="guide-diagram" aria-label="Van A naar B en over dezelfde route terug"><b>A</b><i className="two-way"/><b>B</b><span className="diagram-caption">↩ dezelfde route terug</span></div><p>Plan alleen je heenweg. Looply kopieert de volledige route in omgekeerde richting terug naar de start. De afstand en tijd tellen beide richtingen mee.</p><p><strong>Voorbeeld:</strong> 3 km langs het water naar een brug wordt 6 km heen en terug. Kies <strong>Heen & terug</strong> en voeg alleen punten voor de heenweg toe.</p><p className="guide-note">Controleer zelf eventuele richtingbeperkingen: de terugweg is een kopie en wordt niet apart berekend.</p></div>
<details className="guide-details" open><summary>Paden volgen of handmatig tekenen?</summary><p><strong>Volg de paden aan:</strong> nieuwe segmenten gebruiken voetgangersrouting van openrouteservice. Hiervoor is een API-sleutel nodig.</p><p><strong>Volg de paden uit:</strong> nieuwe segmenten worden rechte, gestreepte lijnen. Ze zijn niet gecontroleerd op beloopbaarheid en kunnen dwars door water of gebouwen gaan. Hiervoor is geen sleutel nodig.</p><p>De schakelaar geldt voor <strong>nieuwe segmenten</strong>; bestaande lijnen worden niet automatisch omgezet. Je kunt beide modi in één route combineren. Verwijder en voeg een punt opnieuw toe als je het aankomende segment met een andere modus wilt maken.</p><button className="text-button" onClick={onSettings}><Settings size={14}/>API-sleutel instellen</button></details>
<details className="guide-details"><summary>Routepunten aanpassen en fouten herstellen</summary><p>Selecteer een punt in de lijst of op de kaart. Kies <strong>Verplaatsen</strong> en tik de nieuwe positie aan, of versleep de marker. Met de pijltjes verander je de volgorde; met <strong>Invoegen</strong> plaats je een punt na het geselecteerde punt.</p><p><strong>Omkeren</strong> keert de routevolgorde om. Berekende routes worden waar nodig opnieuw berekend; handmatige en geïmporteerde geometrie worden omgekeerd. Gebruik de pijlen boven de kaart voor ongedaan maken of opnieuw uitvoeren.</p><p>Bij een rekenfout blijft de vorige lijn vervaagd zichtbaar. De afstand is dan verouderd en GPX-export is geblokkeerd. Je kunt wel een concept opslaan en later opnieuw proberen.</p></details>
<details className="guide-details"><summary>Afstand, tempo en geschatte tijd</summary><p>De afstand volgt de volledige routelijn. De tijd wordt berekend met je tempo onder <strong>Jouw tempo</strong>: 5 km bij 6:00 min/km is ongeveer 30 minuten. Stops en persoonlijke inspanning zijn niet meegerekend.</p><p>Bij <strong>Rondje</strong> telt de verbinding terug naar start mee; bij <strong>Heen & terug</strong> telt de heenweg dubbel.</p></details>
<details className="guide-details"><summary>Een bestaande GPX-route gebruiken</summary><p>Kies <strong>GPX importeren</strong>, selecteer een bestand en controleer de preview. Zijn er meerdere tracks, kies dan de gewenste track. Na opslaan vind je hem onder <strong>Mijn routes</strong>.</p><p>De oorspronkelijke lijn en onderbrekingen blijven behouden. Je kunt de route omkeren en metadata aanpassen. Kies <strong>Maak bewerkbare kopie</strong> om er routepunten van te maken. Die kopie wordt opnieuw berekend en kan afwijken; het opgeslagen origineel blijft bestaan.</p><p>Een bestand met alleen losse markeringen is geen hardlooproute. Looply bewaart die markeringen apart en verzint geen verbindingslijnen.</p></details>
<details className="guide-details"><summary>Opslaan, exporteren en meenemen</summary><p>Geef je route via <strong>Route opslaan</strong> een naam. Via <strong>Mijn routes</strong> kun je hem opnieuw openen, dupliceren of favoriet maken. Bewerkingen worden ook als apart concept bewaard.</p><p>Gebruik <strong>GPX exporteren</strong> voor je sportapp of een geschikt horloge. Je browser biedt delen of een download aan. Ondersteuning voor import en afslagaanwijzingen verschilt per apparaat.</p><p>Routes staan alleen in deze browser op dit apparaat. Maak via <strong>Instellingen → Volledige backup downloaden</strong> een JSON-backup om ook tags, punten en segmentmodi te bewaren. GPX is geen volledige appbackup.</p></details>
<p className="privacy-note"><Info size={15}/>Kaartdata garandeert geen toegankelijk of veilig pad. Je locatie tonen of volgen in de geopende app is geen afslag­navigatie of activiteitopname.</p>
<a className="guide-download" href="/handleiding.md" download><Download size={15}/>Handleiding downloaden (.md)</a><button className="primary full" onClick={onClose}>Tijd voor een rondje<ArrowRight size={17}/></button></>;
}
