import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,Eye,EyeOff,KeyRound,LoaderCircle,Trash2} from 'lucide-react';
import {getRoutingKey,routingHeaders,setRoutingKey} from './routingKey';
import {clearRoutingCache} from './routing';
export default function RoutingSettings({serverConfigured,onGuide}:{serverConfigured:boolean|null;onGuide:()=>void}) {
  const [saved,setSaved]=useState(getRoutingKey),[input,setInput]=useState(getRoutingKey),[visible,setVisible]=useState(false),[testing,setTesting]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false),[verified,setVerified]=useState(false);
  const pending=useRef<AbortController|null>(null);
  useEffect(()=>()=>pending.current?.abort(),[]);
  function cancelTest(){pending.current?.abort();pending.current=null;setTesting(false);setVerified(false);}
  function save(){cancelTest();try{const persisted=setRoutingKey(input);clearRoutingCache();setSaved(input.trim());setInput(input.trim());setFailed(false);setMessage(input.trim()?(persisted?'Sleutel opgeslagen voor dit tabblad. Je kunt nu routes berekenen.':'Sleutel actief zolang deze pagina open blijft; sessieopslag is niet beschikbaar.'):'Persoonlijke sleutel verwijderd.');}catch(e){setFailed(true);setMessage((e as Error).message)}}
  function remove(){cancelTest();setRoutingKey('');clearRoutingCache();setInput('');setSaved('');setVisible(false);setFailed(false);setMessage(serverConfigured?'Persoonlijke sleutel verwijderd. De serverconfiguratie wordt weer gebruikt.':'Sleutel verwijderd. Handmatig plannen en GPX blijven beschikbaar.');}
  async function test(){cancelTest();const controller=new AbortController();pending.current=controller;setTesting(true);setMessage('Verbinding met openrouteservice controleren…');setFailed(false);try{const response=await fetch('/api/routing-key/test',{method:'POST',headers:routingHeaders(input.trim()),body:'{}',signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'De verbinding kon niet worden getest.');if(pending.current!==controller)return;setVerified(true);setMessage(input.trim()!==saved?'Verbinding geslaagd. Kies Opslaan om deze sleutel te gebruiken.':'Verbinding geslaagd. Voetgangersrouting is beschikbaar.');}catch(e){if(controller.signal.aborted)return;setFailed(true);setMessage((e as Error).message)}finally{if(pending.current===controller){pending.current=null;setTesting(false)}}}
  return <div className="settings-section routing-settings"><h3><KeyRound size={17}/>Kaarten & routing</h3><div className="provider-status"><span className={`status-dot ${saved||serverConfigured?'':'amber'}`}/>{saved?'Persoonlijke API-sleutel ingesteld':serverConfigured?'Routing via serverconfiguratie':serverConfigured===null?'Serverconfiguratie controleren…':'API-sleutel nodig voor routes over paden'}</div>
    <p>Gebruik je eigen openrouteservice-sleutel voor <strong>Volg de paden</strong>. Kaarten, zoeken, handmatige segmenten en GPX-import werken zonder sleutel.</p>
    <label htmlFor="routing-api-key">openrouteservice API-sleutel</label><div className="key-input"><input id="routing-api-key" type={visible?'text':'password'} value={input} maxLength={4096} placeholder="Plak hier je API-sleutel" autoComplete="off" autoCapitalize="none" spellCheck={false} onChange={e=>{cancelTest();setInput(e.target.value);setMessage('')}}/><button type="button" aria-label={visible?'API-sleutel verbergen':'API-sleutel tonen'} aria-pressed={visible} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>
    <div className="key-actions"><button className="primary" disabled={!input.trim()||input.trim()===saved} onClick={save}><Check size={15}/>Opslaan</button><button className="secondary" disabled={testing||(!input.trim()&&!serverConfigured)} onClick={()=>void test()}>{testing?<LoaderCircle className="spin" size={15}/>:<KeyRound size={15}/>}Test verbinding</button>{saved&&<button className="text-button" onClick={remove}><Trash2 size={14}/>Verwijderen</button>}</div>
    {message&&<p className={`key-feedback ${failed?'failure':verified?'success':''}`} role={failed?'alert':'status'}>{message}</p>}
    <p className="key-storage-note">Bewaard voor dit browsertabblad, ook na vernieuwen. De sleutel gaat via de Looply-server uitsluitend naar openrouteservice; hij wordt niet op de server opgeslagen en komt niet in routebackups. De test gebruikt één aanvraag voor een vaste voorbeeldroute, niet je eigen locatie.</p>
    <details className="key-instructions" open={!saved&&!serverConfigured}><summary>Waar haal ik een API-sleutel?</summary><ol><li>Open het <a href="https://account.heigit.org/" target="_blank" rel="noopener noreferrer">HeiGIT-accountdashboard <ArrowUpRight size={12}/></a> van openrouteservice.</li><li>Maak een account aan of log in. Bevestig je e-mailadres als daarom wordt gevraagd.</li><li>Kopieer je Standard API key uit het dashboard.</li><li>Plak de sleutel hierboven, kies <strong>Test verbinding</strong> en daarna <strong>Opslaan</strong>.</li></ol><p>Bekijk je actuele limieten en verbruik in het dashboard. <a href="https://api.heigit.org/" target="_blank" rel="noopener noreferrer">Officiële API-informatie <ArrowUpRight size={12}/></a></p></details>
    <button className="text-button" onClick={onGuide}>Handleiding voor alle routeopties <ArrowUpRight size={15}/></button>
  </div>;
}
